# Configuration for simulation run

n_iterations: 5

sample_size: 10
n_groups: 2

n_vars: 3

feature_spec:
  dist: "binom"
  size: 1
  prob: 0.5

tolerance: 0.05
threshold: 0.95

out_dir: "results/test1"
