# Configuration for simulation run

n_iterations: # (large) integer

sample_size: # integer
n_groups: # (small) integer

n_vars: # integer

feature_spec:
  dist: "binom"
  size: 1
  prob: 0.5

tolerance: # (small) number between 0 and 1
threshold: # (large) number between 0 and 1

random_seed: # integer

out_dir: # string
